### ISSUE TITLE
`computeProposerIndex` to return and propagate an error?

### ISSUE THREAD

**Issue by gnattishness** [protolambda/zrnt#18]
In spec v0.9.x, [`compute_proposer_index`](https://github.com/ethereum/eth2.0-specs/blob/v0.9.1/specs/core/0_beacon-chain.md#compute_proposer_index) asserts `indices > 0`, where previously this was unguarded and would result in a `ZeroDivisionError` (e.g. in [`get_beacon_proposer_index`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.4/specs/core/0_beacon-chain.md#get_beacon_proposer_index)).

Now that this is explicitly checked in the python spec, should ZRNT return and propagate an error in order to maintain equivalence?

**Comment by gnattishness** [comment]
This is based on my understanding of the following error behavior/equivalence in the 2 specs:

error type | ZRNT | Pyspec
------|----------|-----
expected error/crash | Go error return | AssertionError or IndexError
serious crash, bug | Go panic | Other python exceptions

**Comment by protolambda** [comment]
Closing some old issues, this is fixed here: https://github.com/protolambda/zrnt/blob/db498edef8d04803c68a15980b4aa467be84357f/eth2/beacon/epochs_context.go#L12
