### ISSUE TITLE
Suggested re-structuring

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/zrnt#2]
1) Don't have a separate folder for `genesis` (it only has one file in it, namely `genesis.go`
2) Remove `enc_helpers.go` from `eth2/beacon/` because it's not part of the state transition function.
3) Put `deltas_computation` inside of `epoch_processing`
4) Remove `debug_format` outside of `eth2/util/`. Similar for `deltas.go` maybe.
5) `helpers.go` only has a single small function (`FindInAndOutValidators`). Can it be put elsewhere?

**Comment by protolambda** [comment]
1) Folders in Go are a bit more meaningful: they define packages. If we want to keep genesis logic to be separate from the main code, and have a 1-way dependency (beacon code consumed by genesis code), a package like currently works best. If it stays low-weight in the future I may consider merging it into the "core" however.
2) I'm afraid encoding helper functions cannot bound to the data types outside of the package. I may move out just the encoding functions however
3) Will wait this one out. Deltas system is quite useful in testing, and I like separation of the default epoch transition (which mutates state) and deltas computation (which is pure)
4) :+1:
5) It could, but after talking with the Sigma Prime guys, I think there are even more efficient ways of doing in/out conditions. (mark a "status" for each validator in O(n), for each set, and then iterate status objects. Possibly with an (abstracted) bitfield for even more efficiency) Will try implementing this new technique first.

**Comment by protolambda** [comment]
1) Fixed
2) Fixed. Not perfect, but better. Moved functionality to util package. But still have to attach it to the type, which needs to be in the same package. That lives in data-types now.
3) Prefer not to, different method type and intentions, good to test separately
4) Fixed
5) Fixed. Using typing for sorted-validator lists now, and with these guarantees it can do a much more efficient join (which lives as a function attached to the sorted index list type)
