### ISSUE TITLE
Panic when deserializing invalid public keys

### ISSUE THREAD

**Issue by zedt3ster** [protolambda/zrnt#21]
# Issue

Fuzzing activities (see [beacon-fuzz](https://github.com/sigp/beacon-fuzz)) have identified a panic in the `parsePubkeys` function of ZRNT (see [this specific line](https://github.com/protolambda/zrnt/blob/master/eth2/util/bls/bls_util_on.go#L34)).

Specifically, a `process_attester_slashing` fuzzer, used with a specific, mutated beacon state, has triggered this crash.

# Steps to reproduce

See the following files for further details:

- [Beacon State SSZ file](https://github.com/sigp/beacon-fuzz-artefacts/blob/master/crashes/zrnt/bls-key-deserialization/panic_zrnt_blsPublicKeyDeserialize_beaconstate.ssz)
- [Attester Slashing SSZ file](https://github.com/sigp/beacon-fuzz-artefacts/blob/master/crashes/zrnt/bls-key-deserialization/panic_zrnt_blsPublicKeyDeserialize_attester_slashing.ssz)
- [More detailed information](https://github.com/sigp/beacon-fuzz-artefacts/blob/master/crashes/zrnt/bls-key-deserialization/panic_zrnt_blsPublicKeyDeserialize.md)

# Recommended action

Avoid panicking when possible and propagate the error to the caller.

**Comment by protolambda** [comment]
Closing some old issues, this was fixed a while ago, but now that I merged in ZRNT-tree3 branch, I'm just making sure the fix was included. Fixed here: https://github.com/protolambda/zrnt/blob/db498edef8d04803c68a15980b4aa467be84357f/eth2/util/bls/bls_util_on.go#L47
