### ISSUE TITLE
Attestation errors

### ISSUE THREAD

**Issue by holiman** [protolambda/zrnt#3]
Looking through the code a bit to get a better understanding of the entire flow. Found this:

https://github.com/protolambda/zrnt/blob/master/eth2/beacon/block_processing/block_attestation.go#L67

```golang
	if targetEpoch == state.Epoch() {
		state.CurrentEpochAttestations = append(state.CurrentEpochAttestations, pendingAttestation)
	} else {
		state.PreviousEpochAttestations = append(state.CurrentEpochAttestations, pendingAttestation)
}
```
should probably be 
```golang
	if targetEpoch == state.Epoch() {
		state.CurrentEpochAttestations = append(state.CurrentEpochAttestations, pendingAttestation)
	} else {
		state.PreviousEpochAttestations = append(state.PreviousEpochAttestations, pendingAttestation)
}
```
Also, I'm curious.. The call to `ProcessAttestation` will modify the `state` when processing attestations, and if the last attestation fails, the previous ones in the block will be added to the current/previous anyway. 

```golang
		if err := ProcessAttestation(state, &attestation); err != nil {
			return err
}
```
EDIT: ah, I guess that is ok, because the error will cause the entire state to be thrown away.

And thirdly, since you're just appending attestations, what is to prevent the same attestation from getting added again and again?

**Comment by protolambda** [comment]
1) Probably copy paste error. Made a quick update to latest dev last week, but did not have the chance to test and verify
2) Block processing has error propagation, and if an error occurs, the state is thrown away (as undoing changes is simply to error-prone)
3) That's something from the ETH 2.0 spec, will take a look at next code update.
