### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/zrnt#6]
1. Soon we should be using 4-byte fork versions everywhere (see [this commit](https://github.com/ethereum/eth2.0-specs/pull/964/files)) without the need to convert back and forth to uint32, so fork.go can probably go. Since the `GENESIS_FORK_VERSION` is 4 zero bytes, there's no need to even define the constant.
2. `GetEmptyBlock` and `GetTemporaryBlockHeader` are now gone. I would then put the containers in `block.go` into `containers.go` because they are containers.
3. Run https://github.com/mvdan/gofumpt, for example to fix some empty lines at the start of functions.
4. Run https://github.com/golangci/golangci-lint to automatically find bugs 🎉 
5. Is `utils/hex/` part of consensus? If so, can it go away?
6. I'm tempted to merge all the files in the `transition/` folder. All four files fit in 100 lines, and that way we can get a birds-eye view of all the transition logic in one file. You can then remove the folder and move `transition.py` one directory up.

**Comment by protolambda** [comment]
1. removed it a while ago.
2. done a quite a while ago
3. gofumpt is still on the list. But have the report-card badge in the readme, which runs the same linters, incl some from golangci-lint, getting A+. And there are so many other meta-linters. I will look into it after the 0.8 update.
4. see 3
5. removed the encoder. But need the decoder for tests. May move it somewhere else at some point
6. Not as tempted. Go style is generally short small names, and 1 responsibility per file (with 1 testing file next to it). Looking to go more in that direction; split up the state.go file, now that getters/modification/etc. are all nicely categorized in 0.8. Besides, this enables me to use build constraints for part of the functionality, to start supporting phase-1 builds.
